# Copyright (c) 2021-2022, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: broker-external
  name: broker-external
spec:
  {{- if and .Values.loadBalancer.enabled }}
  type: LoadBalancer
  ports:
  - name: external-lb
    port: 92
    targetPort: 9092
    protocol: TCP
  {{- else }}
  type: NodePort
  ports:
  - name: external-np
    port: 9092
    targetPort: {{ .Values.brokerExternal.brokerPort}}
    nodePort: {{ .Values.brokerExternal.brokerPort}}
    protocol: TCP
  {{- end }}
  selector:
    app.kubernetes.io/name: broker
